### ISSUE TITLE
Wrong author label for comments

### ISSUE THREAD

**Issue by TheYahya** [ysarbabi/thewhite#1]
If it's a reply to author comment by a not author it's labeled as author.

[![screenshot](https://user-images.githubusercontent.com/15307244/35879243-f55654e4-0b8f-11e8-8fed-fc5faabe6c6d.png)](https://theyahya.com/blog/in-search-of-lost-time/)

**Comment by TheYahya** [comment]
Fixed at [29c50d3](https://github.com/TheYahya/thewhite/commit/29c50d31576e9246d8d3f9a797d401c8c50627e2)

**Comment by abbas980301** [comment]
Hey
It's my comment in image :grinning:
