### ISSUE TITLE
Nav-Menus dosn't work!

### ISSUE THREAD

**Issue by theuser17** [ysarbabi/thewhite#10]
فهرست‌ها کار نمیکنه و بعد از ایجاد فهرست و تنظیمش، نمایش داده نمیشه
دو مکان برای نمایش فهرست وجود داره به نام هدر و فوتر، که هیچ کدومش کار نکرد

**Comment by TheYahya** [comment]
<div dir=rtl>
ممنون ازت که قالب رو نصب کردی و باگ‌ها رو گزارش دادی ☺️ 

اگر آخرین ورژن رو نصب کردی و فهرست‌ها با url کامل شامل http ثبت شده و عنوان هم داره، نباید مشکلی داشته باشه.

ولی اگر وبلاگ آنلاین هست، میشه لینکش رو بهم بدی تا ی نگاه بندازم.

آگر بتونی از فرایند چندتا اسکرین‌شات بذاری خیلی کمک کننده‌ست که فهمم مشکل رو


</div>

**Comment by theuser17** [comment]
خواهش میکنم 😉
اسکرین شات از صفحه مدیریت سایت، قسمت فهرستها:
http://s9.picofile.com/file/8355939342/Nav2.png

اسکرین شات از سایت:
http://s9.picofile.com/file/8355939034/Site_ScreenShot2.png

**Comment by TheYahya** [comment]
<div dir="rtl">
طبق عکسی که فرستادم، باید از قسمت «تنظیمات پوسته» این موارد رو تغییر بدی

اگه بازم اوکی نشد، بهم ایمیل بده با هم بررسی کنیم: yahya.arbabi در جیمیل ☺️ 
</div>
<br/><br/>
<img width="1698" alt="Screen Shot 2019-03-26 at 11 37 54 PM" src="https://user-images.githubusercontent.com/15307244/55026293-595db600-5020-11e9-90c5-d0e4db064636.png">

**Comment by theuser17** [comment]
تقریبا اوکی شد، و هر لینکی که بخوام میشه اضافه کرد؛ ولی مشکل اینه که نمیشه ترتیب رو تغییر داد
مثلا خودش اومده دوتا برگه وردپرس رو گذاشته، بعد لینکهای من رو نمایش میده! خب من چطوری لینک "صفحه اصلی" یا همون "خانه" رو بذارم؟ آخه باید قبل از اونا قرار بگیره

**Comment by TheYahya** [comment]
متاسفانه این قابلیت ممکن نیست
