### ISSUE TITLE
Justify titles in mobile view

### ISSUE THREAD

**Issue by 01sadra** [ysarbabi/thewhite#2]
Long titles in mobile view seem messy as you can see. there is a huge space between date and title.

![screen shot 2018-03-12 at 09 37 48](https://user-images.githubusercontent.com/19735199/37268053-24d24288-25d9-11e8-812e-6b40e61fd598.png)

**Comment by TheYahya** [comment]
Thanks @01sadra, I just [fix it](https://github.com/TheYahya/thewhite/commit/cab92810fd16b5078a532488af2daf3d09d09683).
