### ISSUE TITLE
Images not loading in mobile view

### ISSUE THREAD

**Issue by ArmanJR** [ysarbabi/thewhite#3]
It seems that images don't load in mobile devices for the first time user opens a post and it needs a page refresh to load all the images.

**Comment by TheYahya** [comment]
Thanks @ArmanJR for your feedback,
But could you describe the bug more specific. On which device and browser did you encounter with this issue? And even attach an screenshot if you would.

**Comment by ArmanJR** [comment]
Thank you for your support.
I face this bug on iOS, both Safari & Chrome:

http://bayanbox.ir/info/3258831549887084270/1D5A6D9F-AA07-4BF2-B907-BFE152BC3C2B

**Comment by TheYahya** [comment]
I just check it on IOS and some other devices, but there wasn't any problem!
Could be an issue on **your device** or **Internet provider**, I can't think of anything else.
